(ns editor-test.main
  (:require
   ["package:flutter/material.dart" :as m]
   ["package:flutter/foundation.dart" :as foundation]
   [cljd.flutter :as f]
   [rich-editor.ui.editor-main :refer [mongol-editor-view]]
   [rich-editor.services.virtual-keyboard-service :as vk-service]))

(defn main []
  (m.WidgetsFlutterBinding/ensureInitialized)
  
  ;; Initialize virtual keyboard service on mobile platforms
  (when (or 
          (= foundation/defaultTargetPlatform m/TargetPlatform.iOS)
          (= foundation/defaultTargetPlatform m/TargetPlatform.android)) 
    (vk-service/initialize!))

  (f/run
   (f/widget
    (m/MaterialApp
     .title "MGL Rich Text Editor Test"
     .debugShowCheckedModeBanner false
     .theme (m/ThemeData
             .brightness m.Brightness/dark
             .useMaterial3 true)
     .home (m/Scaffold
            .appBar (m/AppBar
                     .elevation 0)
            .body (mongol-editor-view)
            ;; (m/Text "Hello, World!"))
            )))))